#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Tie: Default monitor
#bspc monitor -d I II III IV V VI VII VIII IX X

# Tie: My monitor
#bspc monitor eDP -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI-A-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Tie: Default rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Yad state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Tie: My rules
TEST_CMD=$(xrandr --listmonitors | wc -l)
if [[ $TEST_CMD == 3 ]]; then
  # if external monitor is connected 
  bspc monitor HDMI-A-0 -d 1 2 3 4 5
  bspc monitor eDP -d 6 7 8 9 10
  bspc rule -a Google-chrome desktop='2'
  bspc rule -a jetbrains-pycharm desktop='3'
  bspc rule -a jetbrains-webstorm desktop='3'
  bspc rule -a Code desktop='3'
  bspc rule -a TelegramDesktop desktop='5'
else
  bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
  bspc rule -a Google-chrome desktop='2'
  bspc rule -a jetbrains-pycharm desktop='3'
  bspc rule -a jetbrains-webstorm desktop='3'
  bspc rule -a Code desktop='3'
  bspc rule -a TelegramDesktop desktop='5'
fi


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

